- name: "Apache installation"
  hosts: all
  tasks:
    - name: "Installation du packahge apache"
      ansible.builtin.apt:
        name: "apache2"
        state: "present"
    - name: "Démarrage du service"
      ansible.builtin.service:
        name: "apache2"
        state: "started"
        enabled: "yes"
    - name: "Copie du ficher dans le repertoire"
      ansible.builtin.copy:
        src: "test.html"
        remote_src: "yes"
        dest: "/var/www/html"
        owner: "root"
        mode: "preserve"
        group: "root"
