- name: "apache installation"
  hosts: all
  tasks: 
   - name: "Installation du packahge apache"
     apt: 
       name: "apache2"
       state: "present"
   - name: "Démarrage du service"
     service:
       name: "apache2"   
       state:  "started"
       enabled: "yes"
   - name: "copie du ficher dans le repertoire"
     copy:
       src: "test.html"
       dest: "/var/www/html"
       owner: "root"
       group: "root"  

